### ISSUE TITLE
Could you please share example of code on how to use trained models for the text classification?

### ISSUE THREAD

**Issue by negacy** [huseinzol05/NLP-Models-Tensorflow#14]
Hi there, 

Good job for what you have done here. I would like to use trained models using one of your classifiers (for example, gpt-2 or LX-net) on a new input.  Do you have code that will help me use the trained models for inference?

Thanks in advance.

**Comment by huseinzol05** [comment]
You can read from here, https://www.tensorflow.org/guide/saved_model

I will add later based on that documentation, but quite late.
