### ISSUE TITLE
missing embed_seq()

### ISSUE THREAD

**Issue by ytianjao** [huseinzol05/NLP-Models-Tensorflow#17]
https://github.com/huseinzol05/NLP-Models-Tensorflow/blob/master/entity-tagging/7.attention-is-all-you-need.ipynb

def learned_position_encoding(inputs, mask, embed_dim):
    T = tf.shape(inputs)[1]
    outputs = tf.range(tf.shape(inputs)[1])                # (T_q)
    outputs = tf.expand_dims(outputs, 0)                   # (1, T_q)
    outputs = tf.tile(outputs, [tf.shape(inputs)[0], 1])   # (N, T_q)
    outputs = embed_seq(outputs, T, embed_dim, zero_pad=False, scale=False)
    return tf.expand_dims(tf.to_float(mask), -1) * outputs

**Comment by huseinzol05** [comment]
In that notebook, I dont use `learned_position_encoding` function. But you want to use it, let me search back my entire folder.

**Comment by ytianjao** [comment]
thanks!
