### ISSUE TITLE
bug in skip-thought.ipynb 

### ISSUE THREAD

**Issue by guodata** [huseinzol05/NLP-Models-Tensorflow#2]
NLP-Models-Tensorflow/unsupervised-summarization/skip-thought.ipynb 

bugs:
======================================
for i in range(5):
    pbar = tqdm(range(0, len(middle), batch_size), desc='train minibatch loop')
    for p in pbar:

should be
======================================
for k in range(5):
    pbar = tqdm(range(0, len(middle), batch_size), desc='train minibatch loop')
    for i in pbar:

**Comment by huseinzol05** [comment]
thanks for noticing that, will going to fix that on next commit!

**Comment by huseinzol05** [comment]
Fix! feel free to reopen.
