### ISSUE TITLE
Could you please provide the installation guide for augmentation in Speech2text parts?

### ISSUE THREAD

**Issue by iamweiweishi** [huseinzol05/NLP-Models-Tensorflow#21]
Hi,
I am trying to run the examples in 'speech-to-text'. 
But the caching.ipynb needs the augmentation module.
It seems like this module is not installed by 'pip install augmentation', which does not include the 'change_pitch_speech', 'change_amplitude', ... methods.
so could you pls provide me some infos about the module?
Many thanks.

**Comment by huseinzol05** [comment]
Added [augmentation.py](https://github.com/huseinzol05/NLP-Models-Tensorflow/blob/master/speech-to-text/augmentation.py), I forgot to add it last time, sorry.
