### ISSUE TITLE
why you have so many Chatbot notebooks??  

### ISSUE THREAD

**Issue by deepanshumehtaa** [huseinzol05/NLP-Models-Tensorflow#23]
https://github.com/huseinzol05/NLP-Models-Tensorflow/tree/master/chatbot

**Comment by deepanshumehtaa** [comment]
https://github.com/huseinzol05/NLP-Models-Tensorflow/tree/master/chatbot

**Comment by huseinzol05** [comment]
different models?

**Comment by deepanshumehtaa** [comment]
yes why so??
