### ISSUE TITLE
AssertionError:  assert not np.isnan(cost).  How to solve this NAN error. Thanks in advance.

### ISSUE THREAD

**Issue by ViswanathaReddyGajjala** [huseinzol05/NLP-Models-Tensorflow#3]

**Comment by huseinzol05** [comment]
Which notebook is this?

**Comment by ViswanathaReddyGajjala** [comment]
https://github.com/huseinzol05/NLP-Models-Tensorflow/blob/master/text-classification/65.gpt-2.ipynb

The notebook is for binary classification. I have modified the code for multi-class classification. But, the accuracy is around 55.5 . By using BERT, I am getting around 75. Is it ok to have such a large margin between those two models? Thanks in advance.

**Comment by huseinzol05** [comment]
I am also wondering why GPT-2 is not really powerful, maybe my code is not really a good in structure, I might need to check the GPT-2 inside tensorboard

**Comment by ViswanathaReddyGajjala** [comment]
Have you trained the model in an unsupervised manner?

**Comment by huseinzol05** [comment]
can you elaborate more about unsupervised manner?

**Comment by ViswanathaReddyGajjala** [comment]
Are you using the pre-trained model released by OpenAI?

**Comment by huseinzol05** [comment]
nope, I just took the model code, and train it from scratch. Maybe you can try to do and let me know the result.

**Comment by GraphGrailAi** [comment]
Hi, GPT-2 from OpenAI is not full data they release, as they say, maybe that is the answer
